# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(788, 482)
        Form.setMinimumSize(QtCore.QSize(788, 0))
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.name_app_label = QtWidgets.QLabel(Form)
        self.name_app_label.setScaledContents(True)
        self.name_app_label.setAlignment(QtCore.Qt.AlignCenter)
        self.name_app_label.setObjectName("name_app_label")
        self.verticalLayout.addWidget(self.name_app_label)
        self.search_layout = QtWidgets.QHBoxLayout()
        self.search_layout.setObjectName("search_layout")
        self.search_line = QtWidgets.QLineEdit(Form)
        self.search_line.setMinimumSize(QtCore.QSize(0, 30))
        self.search_line.setObjectName("search_line")
        self.search_layout.addWidget(self.search_line)
        self.search_btn = QtWidgets.QPushButton(Form)
        self.search_btn.setMinimumSize(QtCore.QSize(0, 40))
        self.search_btn.setObjectName("search_btn")
        self.search_layout.addWidget(self.search_btn)
        self.verticalLayout.addLayout(self.search_layout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.predict_layout = QtWidgets.QVBoxLayout()
        self.predict_layout.setObjectName("predict_layout")
        self.pred_label = QtWidgets.QLabel(Form)
        self.pred_label.setObjectName("pred_label")
        self.predict_layout.addWidget(self.pred_label)
        self.pred_line = QtWidgets.QLineEdit(Form)
        self.pred_line.setMinimumSize(QtCore.QSize(80, 30))
        self.pred_line.setMaximumSize(QtCore.QSize(240, 16777215))
        self.pred_line.setText("")
        self.pred_line.setObjectName("pred_line")
        self.predict_layout.addWidget(self.pred_line)
        self.pred_add_delete_layout = QtWidgets.QHBoxLayout()
        self.pred_add_delete_layout.setObjectName("pred_add_delete_layout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.pred_add_delete_layout.addItem(spacerItem)
        self.pred_add_btn = QtWidgets.QPushButton(Form)
        self.pred_add_btn.setMinimumSize(QtCore.QSize(0, 40))
        self.pred_add_btn.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pred_add_btn.setObjectName("pred_add_btn")
        self.pred_add_delete_layout.addWidget(self.pred_add_btn)
        self.pred_delete_btn = QtWidgets.QPushButton(Form)
        self.pred_delete_btn.setMinimumSize(QtCore.QSize(0, 40))
        self.pred_delete_btn.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pred_delete_btn.setObjectName("pred_delete_btn")
        self.pred_add_delete_layout.addWidget(self.pred_delete_btn)
        self.predict_layout.addLayout(self.pred_add_delete_layout)
        self.pred_list = QtWidgets.QListWidget(Form)
        self.pred_list.setMaximumSize(QtCore.QSize(240, 16777215))
        self.pred_list.setObjectName("pred_list")
        self.predict_layout.addWidget(self.pred_list)
        self.pred_load_save_layout = QtWidgets.QHBoxLayout()
        self.pred_load_save_layout.setObjectName("pred_load_save_layout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.pred_load_save_layout.addItem(spacerItem1)
        self.pred_save_btn = QtWidgets.QPushButton(Form)
        self.pred_save_btn.setMinimumSize(QtCore.QSize(0, 40))
        self.pred_save_btn.setMaximumSize(QtCore.QSize(200, 16777215))
        self.pred_save_btn.setObjectName("pred_save_btn")
        self.pred_load_save_layout.addWidget(self.pred_save_btn)
        self.predict_layout.addLayout(self.pred_load_save_layout)
        self.horizontalLayout.addLayout(self.predict_layout)
        spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.rules_layout = QtWidgets.QVBoxLayout()
        self.rules_layout.setObjectName("rules_layout")
        self.rules_label = QtWidgets.QLabel(Form)
        self.rules_label.setObjectName("rules_label")
        self.rules_layout.addWidget(self.rules_label)
        self.edit_layout = QtWidgets.QHBoxLayout()
        self.edit_layout.setObjectName("edit_layout")
        self.rule_if_line = QtWidgets.QLineEdit(Form)
        self.rule_if_line.setMinimumSize(QtCore.QSize(150, 30))
        self.rule_if_line.setObjectName("rule_if_line")
        self.edit_layout.addWidget(self.rule_if_line)
        self.rule_then_line = QtWidgets.QLineEdit(Form)
        self.rule_then_line.setMinimumSize(QtCore.QSize(150, 30))
        self.rule_then_line.setObjectName("rule_then_line")
        self.edit_layout.addWidget(self.rule_then_line)
        self.rules_layout.addLayout(self.edit_layout)
        self.rule_add_delete_layout = QtWidgets.QHBoxLayout()
        self.rule_add_delete_layout.setObjectName("rule_add_delete_layout")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.rule_add_delete_layout.addItem(spacerItem3)
        self.rule_add_btn = QtWidgets.QPushButton(Form)
        self.rule_add_btn.setMinimumSize(QtCore.QSize(0, 40))
        self.rule_add_btn.setObjectName("rule_add_btn")
        self.rule_add_delete_layout.addWidget(self.rule_add_btn)
        self.rule_delete_btn = QtWidgets.QPushButton(Form)
        self.rule_delete_btn.setMinimumSize(QtCore.QSize(0, 40))
        self.rule_delete_btn.setObjectName("rule_delete_btn")
        self.rule_add_delete_layout.addWidget(self.rule_delete_btn)
        self.rules_layout.addLayout(self.rule_add_delete_layout)
        self.rules_table = QtWidgets.QTableWidget(Form)
        self.rules_table.setLineWidth(1)
        self.rules_table.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.rules_table.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.rules_table.setObjectName("rules_table")
        self.rules_table.setColumnCount(2)
        self.rules_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.rules_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.rules_table.setHorizontalHeaderItem(1, item)
        self.rules_table.horizontalHeader().setVisible(True)
        self.rules_table.horizontalHeader().setCascadingSectionResizes(True)
        self.rules_table.horizontalHeader().setDefaultSectionSize(147)
        self.rules_table.horizontalHeader().setMinimumSectionSize(93)
        self.rules_table.horizontalHeader().setSortIndicatorShown(True)
        self.rules_table.horizontalHeader().setStretchLastSection(False)
        self.rules_table.verticalHeader().setVisible(False)
        self.rules_table.verticalHeader().setHighlightSections(True)
        self.rules_table.verticalHeader().setSortIndicatorShown(True)
        self.rules_table.verticalHeader().setStretchLastSection(False)
        self.rules_layout.addWidget(self.rules_table)
        self.load_save_layout = QtWidgets.QHBoxLayout()
        self.load_save_layout.setObjectName("load_save_layout")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.load_save_layout.addItem(spacerItem4)
        self.rule_save_btn = QtWidgets.QPushButton(Form)
        self.rule_save_btn.setMinimumSize(QtCore.QSize(0, 40))
        self.rule_save_btn.setMaximumSize(QtCore.QSize(200, 16777215))
        self.rule_save_btn.setObjectName("rule_save_btn")
        self.load_save_layout.addWidget(self.rule_save_btn)
        self.rules_layout.addLayout(self.load_save_layout)
        self.horizontalLayout.addLayout(self.rules_layout)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "ProdApp"))
        self.name_app_label.setText(_translate("Form", "Продукционная модель представления знаний"))
        self.search_line.setText(_translate("Form", "Введите запрос"))
        self.search_btn.setText(_translate("Form", "Поиск"))
        self.pred_label.setText(_translate("Form", "Признаки"))
        self.pred_add_btn.setText(_translate("Form", "Добавить"))
        self.pred_delete_btn.setText(_translate("Form", "Удалить"))
        self.pred_save_btn.setText(_translate("Form", "Сохранить признаки"))
        self.rules_label.setText(_translate("Form", "Правила"))
        self.rule_if_line.setText(_translate("Form", "Если"))
        self.rule_then_line.setText(_translate("Form", "То"))
        self.rule_add_btn.setText(_translate("Form", "Добавить"))
        self.rule_delete_btn.setText(_translate("Form", "Удалить"))
        item = self.rules_table.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Если"))
        item = self.rules_table.horizontalHeaderItem(1)
        item.setText(_translate("Form", "То"))
        self.rule_save_btn.setText(_translate("Form", "Сохранить правила"))

